fix gcc5 FTBFS
ImageManager/VideoThumbnails.cpp:47:22:
error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
     m_pendingRequest = nullptr;

https://gcc.gnu.org/gcc-5/porting_to.html says
"... It is recommended to use the false keyword instead of converting nullptr
to bool."